### ISSUE TITLE
getRawBody timing out... Possible hmac string encoding issue?

### ISSUE THREAD

**Issue by ndickiso** [DanWebb/valid-shopify-request#1]
*Sorry for the ignorance, it's been a while since opening an issue:*

I was stoked to use this lib for authenticating shopify webhooks in firebase functions.. After installing, configuring and a ton of time trouble shooting, I kept getting the following error after I believe the raw-body.getRawBody request eventually timed out, and left me with:

`Security Error - The request was not authentic`

~Weird enough~, this did not *always* happen when testing locally and tunneling through ngrok...

After trying about every other shopify webhook auth middleware, I noticed some discrepancy in how each treated the shopify hmac header string encoding... I'm not exactly clear whether the encoding refers to the encoding of string or the encoding of the bytes in the Buffer... but digging through *valid-shopify-request/dist/hmac-from-body.js* and changing ln.16:
**From**
```js
const hmacHeader = payload.headers['x-shopify-hmac-sha256'];
```
**To**
```js
const hmacHeader = payload.headers['x-shopify-hmac-sha256'].toString(encoding || 'utf8');
```

Then validation was always working correctly! 
Reply if anyone else is having this issue or can explain what I'm doing wrong here. Happy to open **pr** if this is other than an error created on my end... cheers!

---
P.S. if it matters, on README the express example server initialization errored out for me on (V 4.17.1): 
```js
app.server.listen(3000); -> app.listen(3000);
```

**Comment by DanWebb** [comment]
Hey @ndickiso, sorry it's a bit late just getting the headspace to come back round to this one...

First off, great to hear you got this working!

If adding `.toString` to the `hmacHeader` fixed this issue for you, I don't think the `getRawBody` will be where your problem lies. Just because adding this would make no difference to the payload passed into the `getRawBody` call.

The `.toString()` method [doesn't actually take something like 'utf8' as a param](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toString). So all that's returned from it is the same string.

I can only think at some point, possibly in firebase the "x-shopify-hmac-sha256" header comes through as a string object which the `Buffer.from` call [on line L15](https://github.com/DanWebb/valid-shopify-request/blob/master/src/hmac-from-body.ts#L15) doesn't like. 

I can't replicate so I don't know that this is the actual issue but the call to `.toString` doesn't hurt anything. So in the hope it fixes it for some people like yourself I've added it in v1.0.1.
